os: osx
osx_image: xcode8

before_install:
  - brew install boost --universal
  - brew install wxmac
script:
  - cpan App::cpanminus
  - perl Build.PL
  - perl Build.PL --gui

branches:
  only:
    - master
